# humao.rest-client

@baseUrl=http://127.0.0.1
@baseUrl1=https://leo2go-80-me03.dev.sims-cn.com
@baseUrl2=http://lhdg3.dev.k8s.local
@baseUrl3=http://end-zgo-svc.test.svc.cluster.local

@bearer=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJsZW8yZ28tODAtbWUwMy5kZXYuc2ltcy1jbi5jb20iLCJleHAiOjE2MDg1NDQ1MDEsImp0aSI6IjFfcHV2cXR3dmtraGR3NzY0Z2NtY3IxZnUwb241IiwiaWF0IjoxNjA4NTQwOTAxLCJpc3MiOiJsZW8yZ28tODAtbWUwMy5kZXYuc2ltcy1jbi5jb20iLCJuYmYiOjE2MDg1NDA5MDEsInN1YiI6IjEwMDAwMSIsIm5hbSI6Inpnby11c2VyIiwicm9sIjoiYWRtaW4iLCJhdGkiOiIxIn0.0Jl_ZLvNvilM4tTA1mNvloG0ruWo2HWP9mFDHQRY2DJuN-LV7aEbXyOK2AZRHdtf14DllR5_azBfVPB__0F6Lg

###
POST {{baseUrl1}}/api/v1/signin
Content-Type: application/json

{
  "client": "",
  "code": "",
  "password": "123456",
  "username": "zgo1"
}

###
GET {{baseUrl1}}/authz
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Host:
X-Request-Origin-Method: GET

###
GET {{baseUrl3}}/api/lhdg/v2/user
Content-Type: application/json
Authorization: Bearer {{bearer}}
