# humao.rest-client

@base_url=http://127.0.0.1
@base_url1=https://leo2go-80-me03.dev.sims-cn.com
@base_url2=http://lhdg3.dev.k8s.local
@base_url3=http://end-zgo-svc.test.svc.cluster.local

@bearer=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMjcuMC4wLjEiLCJleHAiOjE2MDk5MTg2MTEsImp0aSI6IjF0d3FzeDVzdTV6MmV6a3o1Y2dncmgxZnZhbWszIiwiaWF0IjoxNjA5OTE1MDExLCJpc3MiOiIxMjcuMC4wLjEiLCJuYmYiOjE2MDk5MTUwMTEsInN1YiI6IjEwMDAwMSIsIm5hbSI6Inpnby11c2VyIiwicm9sIjoiYWRtaW4iLCJ4aWQiOiIxIiwiYXRpIjoiMSJ9.tmBbhNCiwt462imoCWcR9E9lOXvTiLrvqaPxkhe_rJWXziiUmy0O2HTbm_zTFxk8uXJuO-DIO8RtCOmimbFuKA

@refresh_token=1rmk9njyq8q4azfsz1wjbk1fva5dodf4cy982c56x

###
POST {{base_url}}/api/ka/v1/signin
Content-Type: application/json

{
  //"captcha": "",
  //"client": "",
  //"code": "",
  //"host": "",
  //"kid": "",
  //"role": "",
  "password": "123456",
  "username": "it-100002"
}

###
GET {{base_url}}/api/ka/v1/signin/refresh?refresh_token={{refresh_token}}
Content-Type: application/json

###
Get {{base_url}}/api/ka/v1/user/current
Content-Type: application/json
Authorization: Bearer {{bearer}}

###
GET {{base_url}}/authz
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Host:
X-Request-Origin-Method: GET

###
GET {{base_url2}}/api/lhdg/v2/user
Content-Type: application/json
Authorization: Bearer {{bearer}}
