// Code generated by entc, DO NOT EDIT.

package menurole

import (
	"time"
)

const (
	// Label holds the string label denoting the menurole type in the database.
	Label = "menu_role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMenuID holds the string denoting the menu_id field in the database.
	FieldMenuID = "menu_id"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"

	// Table holds the table name of the menurole in the database.
	Table = "menu_role"
)

// Columns holds all SQL columns for menurole fields.
var Columns = []string{
	FieldID,
	FieldRoleID,
	FieldUserID,
	FieldMenuID,
	FieldCreator,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// DefaultVersion holds the default value on creation for the version field.
	DefaultVersion int
)
