// Code generated by entc, DO NOT EDIT.

package usermessage

import (
	"time"
)

const (
	// Label holds the string label denoting the usermessage type in the database.
	Label = "user_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDatetime holds the string denoting the datetime field in the database.
	FieldDatetime = "datetime"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldClickClose holds the string denoting the clickclose field in the database.
	FieldClickClose = "click_close"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"

	// Table holds the table name of the usermessage in the database.
	Table = "user_message"
)

// Columns holds all SQL columns for usermessage fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldAvatar,
	FieldTitle,
	FieldDatetime,
	FieldType,
	FieldRead,
	FieldDescription,
	FieldClickClose,
	FieldStatus,
	FieldCreator,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// DefaultVersion holds the default value on creation for the version field.
	DefaultVersion int
)
