basePath: /api
definitions:
  helper.Success:
    properties:
      data:
        description: 响应数据
        type: object
      success:
        description: 请求成功, false
        type: boolean
      traceId:
        description: 方便进行后端故障排除：唯一的请求ID
        type: string
    type: object
  schema.SigninBody:
    properties:
      attach:
        description: reset:重置登入 refresh:刷新令牌
        type: string
      captcha:
        description: 验证码
        type: string
      client:
        description: 应用, 默认为主应用, 为空
        type: string
      code:
        description: 标识码
        type: string
      password:
        description: 密码
        type: string
      role:
        description: 角色
        type: string
      username:
        description: 账户
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: susirc@outlook.com
    name: suisrc
  description: GIN + ENT/SQLX + CASBIN + WIRE
  license: {}
  title: zgo
  version: 0.0.1
paths:
  /authz:
    get:
      consumes:
      - application/json
      description: 授权接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Authorize
      tags:
      - auth
  /signin:
    post:
      consumes:
      - application/json
      description: 登陆
      parameters:
      - description: SigninBody Info
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/schema.SigninBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signin
      tags:
      - sign
  /signin/refresh:
    get:
      consumes:
      - application/json
      description: 刷新令牌
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Refresh
      tags:
      - sign
  /signout:
    get:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Signin
      tags:
      - sign
  /signup:
    post:
      consumes:
      - application/json
      description: 登陆
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signup
      tags:
      - sign
  /user/current:
    get:
      consumes:
      - application/json
      description: 查询当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: user current
      tags:
      - user
  /user/current/access:
    get:
      consumes:
      - application/json
      description: 查询当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: user current access
      tags:
      - user
  /user/current/notices:
    get:
      consumes:
      - application/json
      description: 查询当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: user current notices
      tags:
      - user
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
