basePath: /api/v1
definitions:
  helper.Success:
    properties:
      data:
        description: 响应数据
        type: object
      success:
        description: 请求成功, false
        type: boolean
      traceId:
        description: 方便进行后端故障排除：唯一的请求ID
        type: string
    type: object
  schema.SigninBody:
    properties:
      captcha:
        description: 验证码
        type: string
      client:
        description: 子应用ID
        type: string
      code:
        description: 标识码
        type: string
      host:
        description: 域, 如果无,使用c.Reqest.Host代替
        type: string
      kid:
        description: 授权平台
        type: string
      password:
        description: 密码
        type: string
      role:
        description: 角色
        type: string
      username:
        description: 账户
        type: string
    required:
    - username
    type: object
info:
  contact:
    email: susirc@outlook.com
    name: suisrc
  description: GIN + ENT/SQLX + CASBIN + WIRE
  title: zgo
  version: 0.0.1
paths:
  /authz:
    get:
      consumes:
      - application/json
      description: 授权接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Authorize
      tags:
      - auth
  /signin:
    post:
      consumes:
      - application/json
      description: 登陆
      parameters:
      - description: SigninBody Info
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/schema.SigninBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signin
      tags:
      - sign
  /signin/captcha:
    get:
      consumes:
      - application/json
      description: 推送验证码
      parameters:
      - description: mobile
        in: query
        name: mobile
        type: string
      - description: email
        in: query
        name: email
        type: string
      - description: openid
        in: query
        name: openid
        type: string
      - description: kid
        in: query
        name: kid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Captcha
      tags:
      - sign
  /signin/oauth2/{kid}:
    get:
      consumes:
      - application/json
      description: 第三方授权登陆
      parameters:
      - description: 平台KID
        in: path
        name: kid
        required: true
        type: string
      - description: '返回值类型, 比如: json'
        in: query
        name: result
        type: string
      - description: redirect
        in: query
        name: redirect
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: OAuth2
      tags:
      - sign
  /signin/refresh:
    get:
      consumes:
      - application/json
      description: 刷新令牌
      parameters:
      - description: 刷新令牌
        in: query
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Refresh
      tags:
      - sign
  /signout:
    get:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Signout
      tags:
      - sign
  /signup:
    post:
      consumes:
      - application/json
      description: 登陆
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signup
      tags:
      - sign
  /user/current:
    get:
      consumes:
      - application/json
      description: 查询当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: 查询当前用户信息
      tags:
      - user
  /user/current/access:
    get:
      consumes:
      - application/json
      description: 动态验证用户权限问题
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: 动态验证用户权限问题
      tags:
      - user
  /user/current/notices:
    get:
      consumes:
      - application/json
      description: 查询当前用户消息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: 查询当前用户消息
      tags:
      - user
  /user/oauth2/bind:
    get:
      consumes:
      - application/json
      description: 绑定第三方账户
      parameters:
      - description: 平台KID
        in: query
        name: kid
        required: true
        type: string
      - description: '返回值类型, 比如: json'
        in: query
        name: result
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Bind
      tags:
      - user
  /user/oauth2/unbind:
    get:
      consumes:
      - application/json
      description: 解绑第三方账户
      parameters:
      - description: 平台KID
        in: query
        name: kid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Unbind
      tags:
      - user
  /user/passwd/change:
    post:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: 平台KID
        in: query
        name: kid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: passwd
      tags:
      - user
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
