apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: zgo-irs
spec:
  rules:
    - host: zgo.dev.k8s.local
      http:
        paths:
          - backend:
              serviceName: end-zgo-svc
              servicePort: http
            path: /api/
          - backend:
              serviceName: fnt-zgo-svc
              servicePort: http
            path: /

---
apiVersion: v1
kind: Service
metadata:
  name: end-zgo-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: end-zgo
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-zgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-zgo
  template:
    metadata:
      labels:
        app: end-zgo
    spec:
      imagePullSecrets:
        - name: local-registry
      containers:
        - image: dcr.dev.sims-cn.com/plus/zgo:v2.0.2
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          name: zgo
          #args:
          #  - 'web'
          #  - '-c'
          #  - 'config.toml'
          #command:
          #  - ./zgo
#          volumeMounts:
#            - mountPath: /www/config.toml
#              name: config
#              subPath: config.toml
#      volumes:
#        - name: config-zgo
#          configMap:
#            name: config
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: config-zgo
#data:
#  config.toml: |-
#    runmode = "release"
#    printconfig = false
#    [casbin]
#    enable = true
#    model = "./rbac_restful.conf"
#    policysource = "./rbac_policy.json"
#    [http]
#    port = 80
#    [jwtauth]
#    signingsecret = "J928KDD837C8CLQPZIEC"
#    limittime = 5
#    [mysql]
#    host = "192.168.3.35"
#    port = 33006
#    user = "plus"
#    password = "LdkxiD938Sdc"
#    dbname = "zgo"
#    parameters = "charset=utf8&parseTime=True&loc=Asia%2FShanghai"
#    [i18n]
#    dbenable = false