// Code generated by entc, DO NOT EDIT.

package oauth2token

import (
	"time"
)

const (
	// Label holds the string label denoting the oauth2token type in the database.
	Label = "oauth2token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOauth2ID holds the string denoting the oauth2_id field in the database.
	FieldOauth2ID = "oauth2_id"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldExpiresIn holds the string denoting the expires_in field in the database.
	FieldExpiresIn = "expires_in"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldSyncLock holds the string denoting the sync_lock field in the database.
	FieldSyncLock = "sync_lock"
	// FieldCallCount holds the string denoting the call_count field in the database.
	FieldCallCount = "call_count"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldString1 holds the string denoting the string_1 field in the database.
	FieldString1 = "string_1"
	// FieldString2 holds the string denoting the string_2 field in the database.
	FieldString2 = "string_2"
	// FieldString3 holds the string denoting the string_3 field in the database.
	FieldString3 = "string_3"
	// FieldNumber1 holds the string denoting the number_1 field in the database.
	FieldNumber1 = "number_1"
	// FieldNumber2 holds the string denoting the number_2 field in the database.
	FieldNumber2 = "number_2"
	// FieldNumber3 holds the string denoting the number_3 field in the database.
	FieldNumber3 = "number_3"

	// Table holds the table name of the oauth2token in the database.
	Table = "oauth2_token"
)

// Columns holds all SQL columns for oauth2token fields.
var Columns = []string{
	FieldID,
	FieldOauth2ID,
	FieldAccessToken,
	FieldExpiresIn,
	FieldCreateTime,
	FieldSyncLock,
	FieldCallCount,
	FieldCreator,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
	FieldString1,
	FieldString2,
	FieldString3,
	FieldNumber1,
	FieldNumber2,
	FieldNumber3,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// DefaultVersion holds the default value on creation for the version field.
	DefaultVersion int
)
