// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/suisrc/zgo/app/api"
	"github.com/suisrc/zgo/app/api/manager"
	"github.com/suisrc/zgo/app/model/gpaf"
	"github.com/suisrc/zgo/app/module"
	"github.com/suisrc/zgo/app/oauth2"
	"github.com/suisrc/zgo/app/service"
	"github.com/suisrc/zgo/modules/app"
	"github.com/suisrc/zgo/modules/passwd"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	bundle := NewBundle()
	useEngine := api.NewUseEngine(bundle)
	engine := app.InitGinEngine(useEngine)
	router := app.NewRouter(engine)
	gpa, cleanup, err := gpaf.NewGPA()
	if err != nil {
		return nil, nil, err
	}
	storer, cleanup2, err := module.NewStorer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authOpts := &module.AuthOpts{
		GPA:    gpa,
		Storer: storer,
	}
	auther := module.NewAuther(authOpts)
	casbinAuther := &module.CasbinAuther{
		GPA:    gpa,
		Storer: storer,
		Auther: auther,
	}
	auth := &api.Auth{
		CasbinAuther: casbinAuther,
	}
	validator := &passwd.Validator{}
	mobileSender := service.MobileSender{
		GPA: gpa,
	}
	emailSender := service.EmailSender{
		GPA: gpa,
	}
	threeSender := service.ThreeSender{
		GPA: gpa,
	}
	selector, err := oauth2.NewSelector(gpa, storer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bus, cleanup3, err := module.NewEventBus()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	signin := &service.Signin{
		GPA:            gpa,
		Passwd:         validator,
		Store:          storer,
		MSender:        mobileSender,
		ESender:        emailSender,
		TSender:        threeSender,
		OAuth2Selector: selector,
		Bus:            bus,
	}
	apiSignin := &api.Signin{
		GPA:           gpa,
		Auther:        auther,
		SigninService: signin,
		CasbinAuther:  casbinAuther,
	}
	connect := &api.Connect{
		GPA:           gpa,
		Auther:        auther,
		SigninService: signin,
		CasbinAuther:  casbinAuther,
		SigninAPI:     apiSignin,
	}
	user := service.User{
		GPA:            gpa,
		Store:          storer,
		OAuth2Selector: selector,
	}
	apiUser := &api.User{
		GPA:          gpa,
		UserService:  user,
		CasbinAuther: casbinAuther,
	}
	system := &api.System{
		GPA: gpa,
	}
	weixin := &api.Weixin{
		GPA: gpa,
	}
	managerUser := &manager.User{
		GPA: gpa,
	}
	account := &manager.Account{
		GPA: gpa,
	}
	role := &manager.Role{
		GPA: gpa,
	}
	menu := &manager.Menu{
		GPA: gpa,
	}
	gateway := &manager.Gateway{
		GPA: gpa,
	}
	wire := &manager.Wire{
		User:    managerUser,
		Account: account,
		Role:    role,
		Menu:    menu,
		Gateway: gateway,
	}
	options := &api.Options{
		Engine:       engine,
		Router:       router,
		Auth:         auth,
		Connect:      connect,
		Signin:       apiSignin,
		User:         apiUser,
		System:       system,
		Weixin:       weixin,
		CasbinAuther: casbinAuther,
		ManagerWire:  wire,
	}
	endpoints := api.InitEndpoints(options)
	i18n := &service.I18n{
		GPA:    gpa,
		Bundle: bundle,
	}
	i18nLoader := service.InitI18nLoader(i18n)
	healthz := app.NewHealthz(engine)
	injector := &Injector{
		Engine:     engine,
		Endpoints:  endpoints,
		Bundle:     bundle,
		I18nLoader: i18nLoader,
		Healthz:    healthz,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
