@base_url=http://127.0.0.1

@bearer=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMjcuMC4wLjEiLCJleHAiOjE2MTI1NDk1NTcsImp0aSI6IjFnMXFzY2wxMm56MWo3ZWYxeXRxYXYybWVldDN4cWMiLCJpYXQiOjE2MTI1NDIzNTcsImlzcyI6IjEyNy4wLjAuMSIsIm5iZiI6MTYxMjU0MjM1NywiYXRpIjoiRF9YNkpqWGVLcUEwVlFGcWlwYkJtTjQ3RE5la3dJMV9wMWluVmp4cVNZVT0iLCJhdGMiOiIxMjM5REtjajEyMzlES2NqMTIzOURLY2oxMjM5REtjajEyMzlES2NqIiwibmFtIjoiaXQtMTAwMDA0Iiwib2djIjoiT1JHQ00zNTU4Iiwic2NvIjoic25zYXBpX2xvZ2luIn0.tZHEMJgLB-oYMj1SkfS3sshL78p-GpXxFSe8eREjJRRT-pPu3f4G1ptL-pimVFl1ACNeFs-LouA-pOY6ebdehw

@refresh_token=1g1qscl12nz1j7ef1ytqav2meet3xqc_w0h12uk0nwu7kinizs711g1qsclppn553k52n0o

@code=1g12fe569tootc0tp9hlp1f1c764d_icf32o640emkc0oeet60j

### 登录接口
POST {{base_url}}/api/ka/v1/signin
Content-Type: application/json

{
  // "w": "test",
  "g": "ORGCM3558",
  "scope": "snsapi_login",
  "password": "123456",
  "username": "it-100004"
}

###
Get {{base_url}}/api/ka/v1/signout
Content-Type: application/json
Authorization: Bearer {{bearer}}

###
Get {{base_url}}/api/ka/v1/user/current
Content-Type: application/json
Authorization: Bearer {{bearer}}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/signin/refresh?refresh_token={{refresh_token}}
Content-Type: application/json

### 权限验证接口
GET {{base_url}}/authz
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Host:
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Method: GET
#X-Request-Sys-Role: Operator

### 权限验证接口
GET {{base_url}}/authx
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Host:
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Method: GET

### 清理认证缓存
GET {{base_url}}/authc?sercet=nrob5mplr22g0t
Authorization: Bearer {{bearer}}

### 新建第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/new
Content-Type: application/json
Authorization: Bearer {{bearer}}

### 获取第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/get?code={{code}}
Content-Type: application/json


### 新建第三方令牌
POST {{base_url}}/api/ka/v1/pub/3rd/token
Content-Type: application/json

{
  "password": "123456",
  "username": "it-100002"
}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/pub/3rd/token/refresh?refresh_token={{refresh_token}}
Content-Type: application/json