@base_url=http://127.0.0.1

@bearer=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMjcuMC4wLjEiLCJleHAiOjE2MTE3NDYyNDQsImp0aSI6IjFnMTJmZGoxMmxpbjl4cXczNHB2OWRhZG85dWw4ZjYiLCJpYXQiOjE2MTE3NDI2NDQsImlzcyI6IjEyNy4wLjAuMSIsIm5iZiI6MTYxMTc0MjY0NCwic3ViIjoidTAwMHh4MTAwMDAxMjAyMTAxMTJ4eDEwMDAwMjExMTEwMDAwMDAwMSIsImF0aSI6Imd4dkRVc29kZGhHYjJucldfTV9QcDdzekRjYjZaOEJkWWRUNVphUWw4dUU9IiwibmFtIjoi6LWi6L-q5rWL6K-VMiIsInJvcyI6WyJPcGVyYXRvciIsIk9wZXJhdG9yT3JnIl0sIm9nYyI6Ik9SR0NNMzU1OCJ9.xIFgA0WqFbr0GKekfZbz8xx_QWy6fnfkcx6ROe7atzrEGq7teL4KNFYhSFKvQaEGhEtthOWH9OzFDZuuHI2K2A

@refresh_token=1g12fe569tootc0tp9hlp1f1c764d_xg8q83ti0mr1vtyaw0wb1g12fhlsjekkmpa3fuk

@code=1g12fe569tootc0tp9hlp1f1c764d_icf32o640emkc0oeet60j

### 登录接口
POST {{base_url}}/api/ka/v1/signin
Content-Type: application/json

{
  "password": "123456",
  "username": "it-100002"
}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/signin/refresh?refresh_token={{refresh_token}}
Content-Type: application/json

### 权限验证接口
GET {{base_url}}/authz
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Host:
X-Request-Origin-Method: GET


### 新建第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/new
Content-Type: application/json
Authorization: Bearer {{bearer}}

### 获取第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/get?code={{code}}
Content-Type: application/json


### 新建第三方令牌
POST {{base_url}}/api/ka/v1/pub/3rd/token
Content-Type: application/json

{
  "password": "123456",
  "username": "it-100002"
}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/pub/3rd/token/refresh?refresh_token={{refresh_token}}
Content-Type: application/json