@base_url=http://127.0.0.1

@bearer=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMjcuMC4wLjEiLCJleHAiOjE2MTI1MDA3MjIsImp0aSI6IjFnMXBjbWgxMmwzYWM1ZDM5aWY1bjF6cTI2bHhoYnoiLCJpYXQiOjE2MTI0OTM1MjIsImlzcyI6IjEyNy4wLjAuMSIsIm5iZiI6MTYxMjQ5MzUyMiwic3ViIjoidTAwMHh4MTAwMDAxMjAyMTAxMTJ4eDEwMDAwMjExMTEwMDAwMDAwMSIsImF0aSI6Ii1ZT0JBaGwtdXgtbVFtLVgwcVVtWGlXQlVqLTljQjd3cVNkalkyVHZZYnM9IiwiYXRjIjoiMTIzOURLY2oxMjM5REtjajEyMzlES2NqMTIzOURLY2oxMjM5REtjaiIsIm5hbSI6Iui1oui_qua1i-ivlTIiLCJyb3MiOlsibGhkZzpPcGVyYXRvciIsIk9wZXJhdG9yT3JnIl0sIm9nYyI6Ik9SR0NNMzU1OCIsInNjbyI6InNuc2FwaV9sb2dpbiJ9.u7BtRf09EGe98oDEMJdE9GUNv-VXZeoXssesWM0bmqDVRL4pI4zAnKpbGiw05wOxO2uUJLJwiY7NM1JcUyKpEQ

@refresh_token=1g16unr12lsdmkd6h3x1dznby4k9bme_gf79fkq0u8w2u3dz8ohu1g16unrob5mplr22g0t

@code=1g12fe569tootc0tp9hlp1f1c764d_icf32o640emkc0oeet60j

### 登录接口
POST {{base_url}}/api/ka/v1/signin
Content-Type: application/json

{
  // "w": "test",
  "g": "ORGCM3558",
  "scope": "snsapi_login",
  "password": "123456",
  "username": "it-100002"
}

###
Get {{base_url}}/api/ka/v1/user/current
Content-Type: application/json
Authorization: Bearer {{bearer}}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/signin/refresh?refresh_token={{refresh_token}}
Content-Type: application/json

### 权限验证接口
GET {{base_url}}/authz
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Host:
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Method: GET
#X-Request-Sys-Role: Operator

### 权限验证接口
GET {{base_url}}/authx
Content-Type: application/json
Authorization: Bearer {{bearer}}
X-Request-Origin-Host:
X-Request-Origin-Path: /api/lhdg/v2/user
X-Request-Origin-Method: GET

### 清理认证缓存
GET {{base_url}}/authc?sercet=nrob5mplr22g0t
Authorization: Bearer {{bearer}}

### 新建第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/new
Content-Type: application/json
Authorization: Bearer {{bearer}}

### 获取第三方令牌
GET {{base_url}}/api/ka/v1/pub/3rd/token/get?code={{code}}
Content-Type: application/json


### 新建第三方令牌
POST {{base_url}}/api/ka/v1/pub/3rd/token
Content-Type: application/json

{
  "password": "123456",
  "username": "it-100002"
}

### 令牌刷新接口
GET {{base_url}}/api/ka/v1/pub/3rd/token/refresh?refresh_token={{refresh_token}}
Content-Type: application/json