// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/menuaction"
	"github.com/suisrc/zgo/app/model/ent/predicate"
)

// MenuActionDelete is the builder for deleting a MenuAction entity.
type MenuActionDelete struct {
	config
	hooks      []Hook
	mutation   *MenuActionMutation
	predicates []predicate.MenuAction
}

// Where adds a new predicate to the delete builder.
func (mad *MenuActionDelete) Where(ps ...predicate.MenuAction) *MenuActionDelete {
	mad.predicates = append(mad.predicates, ps...)
	return mad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mad *MenuActionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mad.hooks) == 0 {
		affected, err = mad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenuActionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mad.mutation = mutation
			affected, err = mad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mad.hooks) - 1; i >= 0; i-- {
			mut = mad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mad *MenuActionDelete) ExecX(ctx context.Context) int {
	n, err := mad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mad *MenuActionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: menuaction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menuaction.FieldID,
			},
		},
	}
	if ps := mad.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mad.driver, _spec)
}

// MenuActionDeleteOne is the builder for deleting a single MenuAction entity.
type MenuActionDeleteOne struct {
	mad *MenuActionDelete
}

// Exec executes the deletion query.
func (mado *MenuActionDeleteOne) Exec(ctx context.Context) error {
	n, err := mado.mad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menuaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mado *MenuActionDeleteOne) ExecX(ctx context.Context) {
	mado.mad.ExecX(ctx)
}
