// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/menurole"
)

// MenuRoleCreate is the builder for creating a MenuRole entity.
type MenuRoleCreate struct {
	config
	mutation *MenuRoleMutation
	hooks    []Hook
}

// SetRoleID sets the role_id field.
func (mrc *MenuRoleCreate) SetRoleID(i int) *MenuRoleCreate {
	mrc.mutation.SetRoleID(i)
	return mrc
}

// SetUserID sets the user_id field.
func (mrc *MenuRoleCreate) SetUserID(i int) *MenuRoleCreate {
	mrc.mutation.SetUserID(i)
	return mrc
}

// SetMenuID sets the menu_id field.
func (mrc *MenuRoleCreate) SetMenuID(i int) *MenuRoleCreate {
	mrc.mutation.SetMenuID(i)
	return mrc
}

// SetCreator sets the creator field.
func (mrc *MenuRoleCreate) SetCreator(s string) *MenuRoleCreate {
	mrc.mutation.SetCreator(s)
	return mrc
}

// SetCreatedAt sets the created_at field.
func (mrc *MenuRoleCreate) SetCreatedAt(t time.Time) *MenuRoleCreate {
	mrc.mutation.SetCreatedAt(t)
	return mrc
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (mrc *MenuRoleCreate) SetNillableCreatedAt(t *time.Time) *MenuRoleCreate {
	if t != nil {
		mrc.SetCreatedAt(*t)
	}
	return mrc
}

// SetUpdatedAt sets the updated_at field.
func (mrc *MenuRoleCreate) SetUpdatedAt(t time.Time) *MenuRoleCreate {
	mrc.mutation.SetUpdatedAt(t)
	return mrc
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (mrc *MenuRoleCreate) SetNillableUpdatedAt(t *time.Time) *MenuRoleCreate {
	if t != nil {
		mrc.SetUpdatedAt(*t)
	}
	return mrc
}

// SetVersion sets the version field.
func (mrc *MenuRoleCreate) SetVersion(i int) *MenuRoleCreate {
	mrc.mutation.SetVersion(i)
	return mrc
}

// SetNillableVersion sets the version field if the given value is not nil.
func (mrc *MenuRoleCreate) SetNillableVersion(i *int) *MenuRoleCreate {
	if i != nil {
		mrc.SetVersion(*i)
	}
	return mrc
}

// Mutation returns the MenuRoleMutation object of the builder.
func (mrc *MenuRoleCreate) Mutation() *MenuRoleMutation {
	return mrc.mutation
}

// Save creates the MenuRole in the database.
func (mrc *MenuRoleCreate) Save(ctx context.Context) (*MenuRole, error) {
	if _, ok := mrc.mutation.RoleID(); !ok {
		return nil, &ValidationError{Name: "role_id", err: errors.New("ent: missing required field \"role_id\"")}
	}
	if _, ok := mrc.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New("ent: missing required field \"user_id\"")}
	}
	if _, ok := mrc.mutation.MenuID(); !ok {
		return nil, &ValidationError{Name: "menu_id", err: errors.New("ent: missing required field \"menu_id\"")}
	}
	if _, ok := mrc.mutation.Creator(); !ok {
		return nil, &ValidationError{Name: "creator", err: errors.New("ent: missing required field \"creator\"")}
	}
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		v := menurole.DefaultCreatedAt()
		mrc.mutation.SetCreatedAt(v)
	}
	if _, ok := mrc.mutation.UpdatedAt(); !ok {
		v := menurole.DefaultUpdatedAt()
		mrc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mrc.mutation.Version(); !ok {
		v := menurole.DefaultVersion
		mrc.mutation.SetVersion(v)
	}
	var (
		err  error
		node *MenuRole
	)
	if len(mrc.hooks) == 0 {
		node, err = mrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenuRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mrc.mutation = mutation
			node, err = mrc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mrc.hooks) - 1; i >= 0; i-- {
			mut = mrc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mrc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mrc *MenuRoleCreate) SaveX(ctx context.Context) *MenuRole {
	v, err := mrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mrc *MenuRoleCreate) sqlSave(ctx context.Context) (*MenuRole, error) {
	mr, _spec := mrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	mr.ID = int(id)
	return mr, nil
}

func (mrc *MenuRoleCreate) createSpec() (*MenuRole, *sqlgraph.CreateSpec) {
	var (
		mr    = &MenuRole{config: mrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: menurole.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menurole.FieldID,
			},
		}
	)
	if value, ok := mrc.mutation.RoleID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menurole.FieldRoleID,
		})
		mr.RoleID = value
	}
	if value, ok := mrc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menurole.FieldUserID,
		})
		mr.UserID = value
	}
	if value, ok := mrc.mutation.MenuID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menurole.FieldMenuID,
		})
		mr.MenuID = value
	}
	if value, ok := mrc.mutation.Creator(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menurole.FieldCreator,
		})
		mr.Creator = value
	}
	if value, ok := mrc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: menurole.FieldCreatedAt,
		})
		mr.CreatedAt = value
	}
	if value, ok := mrc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: menurole.FieldUpdatedAt,
		})
		mr.UpdatedAt = value
	}
	if value, ok := mrc.mutation.Version(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menurole.FieldVersion,
		})
		mr.Version = value
	}
	return mr, _spec
}
