// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/oauth2third"
	"github.com/suisrc/zgo/app/model/ent/predicate"
)

// Oauth2ThirdUpdate is the builder for updating Oauth2Third entities.
type Oauth2ThirdUpdate struct {
	config
	hooks      []Hook
	mutation   *Oauth2ThirdMutation
	predicates []predicate.Oauth2Third
}

// Where adds a new predicate for the builder.
func (ou *Oauth2ThirdUpdate) Where(ps ...predicate.Oauth2Third) *Oauth2ThirdUpdate {
	ou.predicates = append(ou.predicates, ps...)
	return ou
}

// SetPlatform sets the platform field.
func (ou *Oauth2ThirdUpdate) SetPlatform(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetPlatform(s)
	return ou
}

// SetAgentID sets the agent_id field.
func (ou *Oauth2ThirdUpdate) SetAgentID(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetAgentID(s)
	return ou
}

// SetSuiteID sets the suite_id field.
func (ou *Oauth2ThirdUpdate) SetSuiteID(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetSuiteID(s)
	return ou
}

// SetAppID sets the app_id field.
func (ou *Oauth2ThirdUpdate) SetAppID(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetAppID(s)
	return ou
}

// SetAppSecret sets the app_secret field.
func (ou *Oauth2ThirdUpdate) SetAppSecret(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetAppSecret(s)
	return ou
}

// SetAuthorizeURL sets the authorize_url field.
func (ou *Oauth2ThirdUpdate) SetAuthorizeURL(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetAuthorizeURL(s)
	return ou
}

// SetTokenURL sets the token_url field.
func (ou *Oauth2ThirdUpdate) SetTokenURL(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetTokenURL(s)
	return ou
}

// SetProfileURL sets the profile_url field.
func (ou *Oauth2ThirdUpdate) SetProfileURL(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetProfileURL(s)
	return ou
}

// SetDomainDef sets the domain_def field.
func (ou *Oauth2ThirdUpdate) SetDomainDef(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetDomainDef(s)
	return ou
}

// SetDomainCheck sets the domain_check field.
func (ou *Oauth2ThirdUpdate) SetDomainCheck(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetDomainCheck(s)
	return ou
}

// SetJsSecret sets the js_secret field.
func (ou *Oauth2ThirdUpdate) SetJsSecret(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetJsSecret(s)
	return ou
}

// SetStateSecret sets the state_secret field.
func (ou *Oauth2ThirdUpdate) SetStateSecret(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetStateSecret(s)
	return ou
}

// SetCallback sets the callback field.
func (ou *Oauth2ThirdUpdate) SetCallback(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetCallback()
	ou.mutation.SetCallback(i)
	return ou
}

// AddCallback adds i to callback.
func (ou *Oauth2ThirdUpdate) AddCallback(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddCallback(i)
	return ou
}

// SetCbEncrypt sets the cb_encrypt field.
func (ou *Oauth2ThirdUpdate) SetCbEncrypt(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetCbEncrypt()
	ou.mutation.SetCbEncrypt(i)
	return ou
}

// AddCbEncrypt adds i to cb_encrypt.
func (ou *Oauth2ThirdUpdate) AddCbEncrypt(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddCbEncrypt(i)
	return ou
}

// SetCbToken sets the cb_token field.
func (ou *Oauth2ThirdUpdate) SetCbToken(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetCbToken(s)
	return ou
}

// SetCbEncoding sets the cb_encoding field.
func (ou *Oauth2ThirdUpdate) SetCbEncoding(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetCbEncoding(s)
	return ou
}

// SetCreator sets the creator field.
func (ou *Oauth2ThirdUpdate) SetCreator(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetCreator(s)
	return ou
}

// SetCreatedAt sets the created_at field.
func (ou *Oauth2ThirdUpdate) SetCreatedAt(t time.Time) *Oauth2ThirdUpdate {
	ou.mutation.SetCreatedAt(t)
	return ou
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (ou *Oauth2ThirdUpdate) SetNillableCreatedAt(t *time.Time) *Oauth2ThirdUpdate {
	if t != nil {
		ou.SetCreatedAt(*t)
	}
	return ou
}

// SetUpdatedAt sets the updated_at field.
func (ou *Oauth2ThirdUpdate) SetUpdatedAt(t time.Time) *Oauth2ThirdUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (ou *Oauth2ThirdUpdate) SetNillableUpdatedAt(t *time.Time) *Oauth2ThirdUpdate {
	if t != nil {
		ou.SetUpdatedAt(*t)
	}
	return ou
}

// SetVersion sets the version field.
func (ou *Oauth2ThirdUpdate) SetVersion(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetVersion()
	ou.mutation.SetVersion(i)
	return ou
}

// SetNillableVersion sets the version field if the given value is not nil.
func (ou *Oauth2ThirdUpdate) SetNillableVersion(i *int) *Oauth2ThirdUpdate {
	if i != nil {
		ou.SetVersion(*i)
	}
	return ou
}

// AddVersion adds i to version.
func (ou *Oauth2ThirdUpdate) AddVersion(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddVersion(i)
	return ou
}

// SetString1 sets the string_1 field.
func (ou *Oauth2ThirdUpdate) SetString1(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetString1(s)
	return ou
}

// SetString2 sets the string_2 field.
func (ou *Oauth2ThirdUpdate) SetString2(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetString2(s)
	return ou
}

// SetString3 sets the string_3 field.
func (ou *Oauth2ThirdUpdate) SetString3(s string) *Oauth2ThirdUpdate {
	ou.mutation.SetString3(s)
	return ou
}

// SetNumber1 sets the number_1 field.
func (ou *Oauth2ThirdUpdate) SetNumber1(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetNumber1()
	ou.mutation.SetNumber1(i)
	return ou
}

// AddNumber1 adds i to number_1.
func (ou *Oauth2ThirdUpdate) AddNumber1(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddNumber1(i)
	return ou
}

// SetNumber2 sets the number_2 field.
func (ou *Oauth2ThirdUpdate) SetNumber2(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetNumber2()
	ou.mutation.SetNumber2(i)
	return ou
}

// AddNumber2 adds i to number_2.
func (ou *Oauth2ThirdUpdate) AddNumber2(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddNumber2(i)
	return ou
}

// SetNumber3 sets the number_3 field.
func (ou *Oauth2ThirdUpdate) SetNumber3(i int) *Oauth2ThirdUpdate {
	ou.mutation.ResetNumber3()
	ou.mutation.SetNumber3(i)
	return ou
}

// AddNumber3 adds i to number_3.
func (ou *Oauth2ThirdUpdate) AddNumber3(i int) *Oauth2ThirdUpdate {
	ou.mutation.AddNumber3(i)
	return ou
}

// Mutation returns the Oauth2ThirdMutation object of the builder.
func (ou *Oauth2ThirdUpdate) Mutation() *Oauth2ThirdMutation {
	return ou.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ou *Oauth2ThirdUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ou.hooks) == 0 {
		affected, err = ou.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*Oauth2ThirdMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ou.mutation = mutation
			affected, err = ou.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ou.hooks) - 1; i >= 0; i-- {
			mut = ou.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ou.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ou *Oauth2ThirdUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *Oauth2ThirdUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *Oauth2ThirdUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ou *Oauth2ThirdUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oauth2third.Table,
			Columns: oauth2third.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauth2third.FieldID,
			},
		},
	}
	if ps := ou.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Platform(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldPlatform,
		})
	}
	if value, ok := ou.mutation.AgentID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAgentID,
		})
	}
	if value, ok := ou.mutation.SuiteID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldSuiteID,
		})
	}
	if value, ok := ou.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAppID,
		})
	}
	if value, ok := ou.mutation.AppSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAppSecret,
		})
	}
	if value, ok := ou.mutation.AuthorizeURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAuthorizeURL,
		})
	}
	if value, ok := ou.mutation.TokenURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldTokenURL,
		})
	}
	if value, ok := ou.mutation.ProfileURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldProfileURL,
		})
	}
	if value, ok := ou.mutation.DomainDef(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldDomainDef,
		})
	}
	if value, ok := ou.mutation.DomainCheck(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldDomainCheck,
		})
	}
	if value, ok := ou.mutation.JsSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldJsSecret,
		})
	}
	if value, ok := ou.mutation.StateSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldStateSecret,
		})
	}
	if value, ok := ou.mutation.Callback(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCallback,
		})
	}
	if value, ok := ou.mutation.AddedCallback(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCallback,
		})
	}
	if value, ok := ou.mutation.CbEncrypt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCbEncrypt,
		})
	}
	if value, ok := ou.mutation.AddedCbEncrypt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCbEncrypt,
		})
	}
	if value, ok := ou.mutation.CbToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCbToken,
		})
	}
	if value, ok := ou.mutation.CbEncoding(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCbEncoding,
		})
	}
	if value, ok := ou.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCreator,
		})
	}
	if value, ok := ou.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2third.FieldCreatedAt,
		})
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2third.FieldUpdatedAt,
		})
	}
	if value, ok := ou.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldVersion,
		})
	}
	if value, ok := ou.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldVersion,
		})
	}
	if value, ok := ou.mutation.String1(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString1,
		})
	}
	if value, ok := ou.mutation.String2(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString2,
		})
	}
	if value, ok := ou.mutation.String3(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString3,
		})
	}
	if value, ok := ou.mutation.Number1(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber1,
		})
	}
	if value, ok := ou.mutation.AddedNumber1(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber1,
		})
	}
	if value, ok := ou.mutation.Number2(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber2,
		})
	}
	if value, ok := ou.mutation.AddedNumber2(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber2,
		})
	}
	if value, ok := ou.mutation.Number3(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber3,
		})
	}
	if value, ok := ou.mutation.AddedNumber3(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber3,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2third.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// Oauth2ThirdUpdateOne is the builder for updating a single Oauth2Third entity.
type Oauth2ThirdUpdateOne struct {
	config
	hooks    []Hook
	mutation *Oauth2ThirdMutation
}

// SetPlatform sets the platform field.
func (ouo *Oauth2ThirdUpdateOne) SetPlatform(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetPlatform(s)
	return ouo
}

// SetAgentID sets the agent_id field.
func (ouo *Oauth2ThirdUpdateOne) SetAgentID(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetAgentID(s)
	return ouo
}

// SetSuiteID sets the suite_id field.
func (ouo *Oauth2ThirdUpdateOne) SetSuiteID(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetSuiteID(s)
	return ouo
}

// SetAppID sets the app_id field.
func (ouo *Oauth2ThirdUpdateOne) SetAppID(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetAppID(s)
	return ouo
}

// SetAppSecret sets the app_secret field.
func (ouo *Oauth2ThirdUpdateOne) SetAppSecret(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetAppSecret(s)
	return ouo
}

// SetAuthorizeURL sets the authorize_url field.
func (ouo *Oauth2ThirdUpdateOne) SetAuthorizeURL(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetAuthorizeURL(s)
	return ouo
}

// SetTokenURL sets the token_url field.
func (ouo *Oauth2ThirdUpdateOne) SetTokenURL(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetTokenURL(s)
	return ouo
}

// SetProfileURL sets the profile_url field.
func (ouo *Oauth2ThirdUpdateOne) SetProfileURL(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetProfileURL(s)
	return ouo
}

// SetDomainDef sets the domain_def field.
func (ouo *Oauth2ThirdUpdateOne) SetDomainDef(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetDomainDef(s)
	return ouo
}

// SetDomainCheck sets the domain_check field.
func (ouo *Oauth2ThirdUpdateOne) SetDomainCheck(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetDomainCheck(s)
	return ouo
}

// SetJsSecret sets the js_secret field.
func (ouo *Oauth2ThirdUpdateOne) SetJsSecret(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetJsSecret(s)
	return ouo
}

// SetStateSecret sets the state_secret field.
func (ouo *Oauth2ThirdUpdateOne) SetStateSecret(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetStateSecret(s)
	return ouo
}

// SetCallback sets the callback field.
func (ouo *Oauth2ThirdUpdateOne) SetCallback(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetCallback()
	ouo.mutation.SetCallback(i)
	return ouo
}

// AddCallback adds i to callback.
func (ouo *Oauth2ThirdUpdateOne) AddCallback(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddCallback(i)
	return ouo
}

// SetCbEncrypt sets the cb_encrypt field.
func (ouo *Oauth2ThirdUpdateOne) SetCbEncrypt(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetCbEncrypt()
	ouo.mutation.SetCbEncrypt(i)
	return ouo
}

// AddCbEncrypt adds i to cb_encrypt.
func (ouo *Oauth2ThirdUpdateOne) AddCbEncrypt(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddCbEncrypt(i)
	return ouo
}

// SetCbToken sets the cb_token field.
func (ouo *Oauth2ThirdUpdateOne) SetCbToken(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetCbToken(s)
	return ouo
}

// SetCbEncoding sets the cb_encoding field.
func (ouo *Oauth2ThirdUpdateOne) SetCbEncoding(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetCbEncoding(s)
	return ouo
}

// SetCreator sets the creator field.
func (ouo *Oauth2ThirdUpdateOne) SetCreator(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetCreator(s)
	return ouo
}

// SetCreatedAt sets the created_at field.
func (ouo *Oauth2ThirdUpdateOne) SetCreatedAt(t time.Time) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetCreatedAt(t)
	return ouo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (ouo *Oauth2ThirdUpdateOne) SetNillableCreatedAt(t *time.Time) *Oauth2ThirdUpdateOne {
	if t != nil {
		ouo.SetCreatedAt(*t)
	}
	return ouo
}

// SetUpdatedAt sets the updated_at field.
func (ouo *Oauth2ThirdUpdateOne) SetUpdatedAt(t time.Time) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (ouo *Oauth2ThirdUpdateOne) SetNillableUpdatedAt(t *time.Time) *Oauth2ThirdUpdateOne {
	if t != nil {
		ouo.SetUpdatedAt(*t)
	}
	return ouo
}

// SetVersion sets the version field.
func (ouo *Oauth2ThirdUpdateOne) SetVersion(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetVersion()
	ouo.mutation.SetVersion(i)
	return ouo
}

// SetNillableVersion sets the version field if the given value is not nil.
func (ouo *Oauth2ThirdUpdateOne) SetNillableVersion(i *int) *Oauth2ThirdUpdateOne {
	if i != nil {
		ouo.SetVersion(*i)
	}
	return ouo
}

// AddVersion adds i to version.
func (ouo *Oauth2ThirdUpdateOne) AddVersion(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddVersion(i)
	return ouo
}

// SetString1 sets the string_1 field.
func (ouo *Oauth2ThirdUpdateOne) SetString1(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetString1(s)
	return ouo
}

// SetString2 sets the string_2 field.
func (ouo *Oauth2ThirdUpdateOne) SetString2(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetString2(s)
	return ouo
}

// SetString3 sets the string_3 field.
func (ouo *Oauth2ThirdUpdateOne) SetString3(s string) *Oauth2ThirdUpdateOne {
	ouo.mutation.SetString3(s)
	return ouo
}

// SetNumber1 sets the number_1 field.
func (ouo *Oauth2ThirdUpdateOne) SetNumber1(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetNumber1()
	ouo.mutation.SetNumber1(i)
	return ouo
}

// AddNumber1 adds i to number_1.
func (ouo *Oauth2ThirdUpdateOne) AddNumber1(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddNumber1(i)
	return ouo
}

// SetNumber2 sets the number_2 field.
func (ouo *Oauth2ThirdUpdateOne) SetNumber2(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetNumber2()
	ouo.mutation.SetNumber2(i)
	return ouo
}

// AddNumber2 adds i to number_2.
func (ouo *Oauth2ThirdUpdateOne) AddNumber2(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddNumber2(i)
	return ouo
}

// SetNumber3 sets the number_3 field.
func (ouo *Oauth2ThirdUpdateOne) SetNumber3(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.ResetNumber3()
	ouo.mutation.SetNumber3(i)
	return ouo
}

// AddNumber3 adds i to number_3.
func (ouo *Oauth2ThirdUpdateOne) AddNumber3(i int) *Oauth2ThirdUpdateOne {
	ouo.mutation.AddNumber3(i)
	return ouo
}

// Mutation returns the Oauth2ThirdMutation object of the builder.
func (ouo *Oauth2ThirdUpdateOne) Mutation() *Oauth2ThirdMutation {
	return ouo.mutation
}

// Save executes the query and returns the updated entity.
func (ouo *Oauth2ThirdUpdateOne) Save(ctx context.Context) (*Oauth2Third, error) {
	var (
		err  error
		node *Oauth2Third
	)
	if len(ouo.hooks) == 0 {
		node, err = ouo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*Oauth2ThirdMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ouo.mutation = mutation
			node, err = ouo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ouo.hooks) - 1; i >= 0; i-- {
			mut = ouo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ouo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *Oauth2ThirdUpdateOne) SaveX(ctx context.Context) *Oauth2Third {
	o, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return o
}

// Exec executes the query on the entity.
func (ouo *Oauth2ThirdUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *Oauth2ThirdUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ouo *Oauth2ThirdUpdateOne) sqlSave(ctx context.Context) (o *Oauth2Third, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oauth2third.Table,
			Columns: oauth2third.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauth2third.FieldID,
			},
		},
	}
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Oauth2Third.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ouo.mutation.Platform(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldPlatform,
		})
	}
	if value, ok := ouo.mutation.AgentID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAgentID,
		})
	}
	if value, ok := ouo.mutation.SuiteID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldSuiteID,
		})
	}
	if value, ok := ouo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAppID,
		})
	}
	if value, ok := ouo.mutation.AppSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAppSecret,
		})
	}
	if value, ok := ouo.mutation.AuthorizeURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldAuthorizeURL,
		})
	}
	if value, ok := ouo.mutation.TokenURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldTokenURL,
		})
	}
	if value, ok := ouo.mutation.ProfileURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldProfileURL,
		})
	}
	if value, ok := ouo.mutation.DomainDef(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldDomainDef,
		})
	}
	if value, ok := ouo.mutation.DomainCheck(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldDomainCheck,
		})
	}
	if value, ok := ouo.mutation.JsSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldJsSecret,
		})
	}
	if value, ok := ouo.mutation.StateSecret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldStateSecret,
		})
	}
	if value, ok := ouo.mutation.Callback(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCallback,
		})
	}
	if value, ok := ouo.mutation.AddedCallback(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCallback,
		})
	}
	if value, ok := ouo.mutation.CbEncrypt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCbEncrypt,
		})
	}
	if value, ok := ouo.mutation.AddedCbEncrypt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldCbEncrypt,
		})
	}
	if value, ok := ouo.mutation.CbToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCbToken,
		})
	}
	if value, ok := ouo.mutation.CbEncoding(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCbEncoding,
		})
	}
	if value, ok := ouo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldCreator,
		})
	}
	if value, ok := ouo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2third.FieldCreatedAt,
		})
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2third.FieldUpdatedAt,
		})
	}
	if value, ok := ouo.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldVersion,
		})
	}
	if value, ok := ouo.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldVersion,
		})
	}
	if value, ok := ouo.mutation.String1(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString1,
		})
	}
	if value, ok := ouo.mutation.String2(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString2,
		})
	}
	if value, ok := ouo.mutation.String3(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2third.FieldString3,
		})
	}
	if value, ok := ouo.mutation.Number1(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber1,
		})
	}
	if value, ok := ouo.mutation.AddedNumber1(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber1,
		})
	}
	if value, ok := ouo.mutation.Number2(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber2,
		})
	}
	if value, ok := ouo.mutation.AddedNumber2(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber2,
		})
	}
	if value, ok := ouo.mutation.Number3(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber3,
		})
	}
	if value, ok := ouo.mutation.AddedNumber3(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: oauth2third.FieldNumber3,
		})
	}
	o = &Oauth2Third{config: ouo.config}
	_spec.Assign = o.assignValues
	_spec.ScanValues = o.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2third.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return o, nil
}
