// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/suisrc/zgo/app/model/ent/resourceuser"
)

// ResourceUser is the model entity for the ResourceUser schema.
type ResourceUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Resource holds the value of the "resource" field.
	Resource string `json:"resource,omitempty"`
	// Creator holds the value of the "creator" field.
	Creator string `json:"creator,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceUser) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // user_id
		&sql.NullString{}, // resource
		&sql.NullString{}, // creator
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
		&sql.NullInt64{},  // version
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceUser fields.
func (ru *ResourceUser) assignValues(values ...interface{}) error {
	if m, n := len(values), len(resourceuser.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ru.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field user_id", values[0])
	} else if value.Valid {
		ru.UserID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field resource", values[1])
	} else if value.Valid {
		ru.Resource = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field creator", values[2])
	} else if value.Valid {
		ru.Creator = value.String
	}
	if value, ok := values[3].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[3])
	} else if value.Valid {
		ru.CreatedAt = value.Time
	}
	if value, ok := values[4].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[4])
	} else if value.Valid {
		ru.UpdatedAt = value.Time
	}
	if value, ok := values[5].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field version", values[5])
	} else if value.Valid {
		ru.Version = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this ResourceUser.
// Note that, you need to call ResourceUser.Unwrap() before calling this method, if this ResourceUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (ru *ResourceUser) Update() *ResourceUserUpdateOne {
	return (&ResourceUserClient{config: ru.config}).UpdateOne(ru)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ru *ResourceUser) Unwrap() *ResourceUser {
	tx, ok := ru.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceUser is not a transactional entity")
	}
	ru.config.driver = tx.drv
	return ru
}

// String implements the fmt.Stringer.
func (ru *ResourceUser) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceUser(")
	builder.WriteString(fmt.Sprintf("id=%v", ru.ID))
	builder.WriteString(", user_id=")
	builder.WriteString(fmt.Sprintf("%v", ru.UserID))
	builder.WriteString(", resource=")
	builder.WriteString(ru.Resource)
	builder.WriteString(", creator=")
	builder.WriteString(ru.Creator)
	builder.WriteString(", created_at=")
	builder.WriteString(ru.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(ru.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", version=")
	builder.WriteString(fmt.Sprintf("%v", ru.Version))
	builder.WriteByte(')')
	return builder.String()
}

// ResourceUsers is a parsable slice of ResourceUser.
type ResourceUsers []*ResourceUser

func (ru ResourceUsers) config(cfg config) {
	for _i := range ru {
		ru[_i].config = cfg
	}
}
