// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/predicate"
	"github.com/suisrc/zgo/app/model/ent/resourcerole"
)

// ResourceRoleUpdate is the builder for updating ResourceRole entities.
type ResourceRoleUpdate struct {
	config
	hooks      []Hook
	mutation   *ResourceRoleMutation
	predicates []predicate.ResourceRole
}

// Where adds a new predicate for the builder.
func (rru *ResourceRoleUpdate) Where(ps ...predicate.ResourceRole) *ResourceRoleUpdate {
	rru.predicates = append(rru.predicates, ps...)
	return rru
}

// SetRoleID sets the role_id field.
func (rru *ResourceRoleUpdate) SetRoleID(i int) *ResourceRoleUpdate {
	rru.mutation.ResetRoleID()
	rru.mutation.SetRoleID(i)
	return rru
}

// AddRoleID adds i to role_id.
func (rru *ResourceRoleUpdate) AddRoleID(i int) *ResourceRoleUpdate {
	rru.mutation.AddRoleID(i)
	return rru
}

// SetResource sets the resource field.
func (rru *ResourceRoleUpdate) SetResource(s string) *ResourceRoleUpdate {
	rru.mutation.SetResource(s)
	return rru
}

// SetCreator sets the creator field.
func (rru *ResourceRoleUpdate) SetCreator(s string) *ResourceRoleUpdate {
	rru.mutation.SetCreator(s)
	return rru
}

// SetCreatedAt sets the created_at field.
func (rru *ResourceRoleUpdate) SetCreatedAt(t time.Time) *ResourceRoleUpdate {
	rru.mutation.SetCreatedAt(t)
	return rru
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (rru *ResourceRoleUpdate) SetNillableCreatedAt(t *time.Time) *ResourceRoleUpdate {
	if t != nil {
		rru.SetCreatedAt(*t)
	}
	return rru
}

// SetUpdatedAt sets the updated_at field.
func (rru *ResourceRoleUpdate) SetUpdatedAt(t time.Time) *ResourceRoleUpdate {
	rru.mutation.SetUpdatedAt(t)
	return rru
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (rru *ResourceRoleUpdate) SetNillableUpdatedAt(t *time.Time) *ResourceRoleUpdate {
	if t != nil {
		rru.SetUpdatedAt(*t)
	}
	return rru
}

// SetVersion sets the version field.
func (rru *ResourceRoleUpdate) SetVersion(i int) *ResourceRoleUpdate {
	rru.mutation.ResetVersion()
	rru.mutation.SetVersion(i)
	return rru
}

// SetNillableVersion sets the version field if the given value is not nil.
func (rru *ResourceRoleUpdate) SetNillableVersion(i *int) *ResourceRoleUpdate {
	if i != nil {
		rru.SetVersion(*i)
	}
	return rru
}

// AddVersion adds i to version.
func (rru *ResourceRoleUpdate) AddVersion(i int) *ResourceRoleUpdate {
	rru.mutation.AddVersion(i)
	return rru
}

// Mutation returns the ResourceRoleMutation object of the builder.
func (rru *ResourceRoleUpdate) Mutation() *ResourceRoleMutation {
	return rru.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (rru *ResourceRoleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rru.hooks) == 0 {
		affected, err = rru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourceRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rru.mutation = mutation
			affected, err = rru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rru.hooks) - 1; i >= 0; i-- {
			mut = rru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (rru *ResourceRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := rru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rru *ResourceRoleUpdate) Exec(ctx context.Context) error {
	_, err := rru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rru *ResourceRoleUpdate) ExecX(ctx context.Context) {
	if err := rru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rru *ResourceRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcerole.Table,
			Columns: resourcerole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcerole.FieldID,
			},
		},
	}
	if ps := rru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rru.mutation.RoleID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldRoleID,
		})
	}
	if value, ok := rru.mutation.AddedRoleID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldRoleID,
		})
	}
	if value, ok := rru.mutation.Resource(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcerole.FieldResource,
		})
	}
	if value, ok := rru.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcerole.FieldCreator,
		})
	}
	if value, ok := rru.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerole.FieldCreatedAt,
		})
	}
	if value, ok := rru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerole.FieldUpdatedAt,
		})
	}
	if value, ok := rru.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldVersion,
		})
	}
	if value, ok := rru.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldVersion,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcerole.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ResourceRoleUpdateOne is the builder for updating a single ResourceRole entity.
type ResourceRoleUpdateOne struct {
	config
	hooks    []Hook
	mutation *ResourceRoleMutation
}

// SetRoleID sets the role_id field.
func (rruo *ResourceRoleUpdateOne) SetRoleID(i int) *ResourceRoleUpdateOne {
	rruo.mutation.ResetRoleID()
	rruo.mutation.SetRoleID(i)
	return rruo
}

// AddRoleID adds i to role_id.
func (rruo *ResourceRoleUpdateOne) AddRoleID(i int) *ResourceRoleUpdateOne {
	rruo.mutation.AddRoleID(i)
	return rruo
}

// SetResource sets the resource field.
func (rruo *ResourceRoleUpdateOne) SetResource(s string) *ResourceRoleUpdateOne {
	rruo.mutation.SetResource(s)
	return rruo
}

// SetCreator sets the creator field.
func (rruo *ResourceRoleUpdateOne) SetCreator(s string) *ResourceRoleUpdateOne {
	rruo.mutation.SetCreator(s)
	return rruo
}

// SetCreatedAt sets the created_at field.
func (rruo *ResourceRoleUpdateOne) SetCreatedAt(t time.Time) *ResourceRoleUpdateOne {
	rruo.mutation.SetCreatedAt(t)
	return rruo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (rruo *ResourceRoleUpdateOne) SetNillableCreatedAt(t *time.Time) *ResourceRoleUpdateOne {
	if t != nil {
		rruo.SetCreatedAt(*t)
	}
	return rruo
}

// SetUpdatedAt sets the updated_at field.
func (rruo *ResourceRoleUpdateOne) SetUpdatedAt(t time.Time) *ResourceRoleUpdateOne {
	rruo.mutation.SetUpdatedAt(t)
	return rruo
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (rruo *ResourceRoleUpdateOne) SetNillableUpdatedAt(t *time.Time) *ResourceRoleUpdateOne {
	if t != nil {
		rruo.SetUpdatedAt(*t)
	}
	return rruo
}

// SetVersion sets the version field.
func (rruo *ResourceRoleUpdateOne) SetVersion(i int) *ResourceRoleUpdateOne {
	rruo.mutation.ResetVersion()
	rruo.mutation.SetVersion(i)
	return rruo
}

// SetNillableVersion sets the version field if the given value is not nil.
func (rruo *ResourceRoleUpdateOne) SetNillableVersion(i *int) *ResourceRoleUpdateOne {
	if i != nil {
		rruo.SetVersion(*i)
	}
	return rruo
}

// AddVersion adds i to version.
func (rruo *ResourceRoleUpdateOne) AddVersion(i int) *ResourceRoleUpdateOne {
	rruo.mutation.AddVersion(i)
	return rruo
}

// Mutation returns the ResourceRoleMutation object of the builder.
func (rruo *ResourceRoleUpdateOne) Mutation() *ResourceRoleMutation {
	return rruo.mutation
}

// Save executes the query and returns the updated entity.
func (rruo *ResourceRoleUpdateOne) Save(ctx context.Context) (*ResourceRole, error) {
	var (
		err  error
		node *ResourceRole
	)
	if len(rruo.hooks) == 0 {
		node, err = rruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourceRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rruo.mutation = mutation
			node, err = rruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rruo.hooks) - 1; i >= 0; i-- {
			mut = rruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (rruo *ResourceRoleUpdateOne) SaveX(ctx context.Context) *ResourceRole {
	rr, err := rruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return rr
}

// Exec executes the query on the entity.
func (rruo *ResourceRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := rruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rruo *ResourceRoleUpdateOne) ExecX(ctx context.Context) {
	if err := rruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rruo *ResourceRoleUpdateOne) sqlSave(ctx context.Context) (rr *ResourceRole, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcerole.Table,
			Columns: resourcerole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcerole.FieldID,
			},
		},
	}
	id, ok := rruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ResourceRole.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := rruo.mutation.RoleID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldRoleID,
		})
	}
	if value, ok := rruo.mutation.AddedRoleID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldRoleID,
		})
	}
	if value, ok := rruo.mutation.Resource(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcerole.FieldResource,
		})
	}
	if value, ok := rruo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcerole.FieldCreator,
		})
	}
	if value, ok := rruo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerole.FieldCreatedAt,
		})
	}
	if value, ok := rruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerole.FieldUpdatedAt,
		})
	}
	if value, ok := rruo.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldVersion,
		})
	}
	if value, ok := rruo.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: resourcerole.FieldVersion,
		})
	}
	rr = &ResourceRole{config: rruo.config}
	_spec.Assign = rr.assignValues
	_spec.ScanValues = rr.scanValues()
	if err = sqlgraph.UpdateNode(ctx, rruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcerole.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return rr, nil
}
