// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/predicate"
	"github.com/suisrc/zgo/app/model/ent/rolerole"
)

// RoleRoleQuery is the builder for querying RoleRole entities.
type RoleRoleQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.RoleRole
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (rrq *RoleRoleQuery) Where(ps ...predicate.RoleRole) *RoleRoleQuery {
	rrq.predicates = append(rrq.predicates, ps...)
	return rrq
}

// Limit adds a limit step to the query.
func (rrq *RoleRoleQuery) Limit(limit int) *RoleRoleQuery {
	rrq.limit = &limit
	return rrq
}

// Offset adds an offset step to the query.
func (rrq *RoleRoleQuery) Offset(offset int) *RoleRoleQuery {
	rrq.offset = &offset
	return rrq
}

// Order adds an order step to the query.
func (rrq *RoleRoleQuery) Order(o ...OrderFunc) *RoleRoleQuery {
	rrq.order = append(rrq.order, o...)
	return rrq
}

// First returns the first RoleRole entity in the query. Returns *NotFoundError when no rolerole was found.
func (rrq *RoleRoleQuery) First(ctx context.Context) (*RoleRole, error) {
	rrs, err := rrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(rrs) == 0 {
		return nil, &NotFoundError{rolerole.Label}
	}
	return rrs[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rrq *RoleRoleQuery) FirstX(ctx context.Context) *RoleRole {
	rr, err := rrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return rr
}

// FirstID returns the first RoleRole id in the query. Returns *NotFoundError when no id was found.
func (rrq *RoleRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rolerole.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (rrq *RoleRoleQuery) FirstXID(ctx context.Context) int {
	id, err := rrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only RoleRole entity in the query, returns an error if not exactly one entity was returned.
func (rrq *RoleRoleQuery) Only(ctx context.Context) (*RoleRole, error) {
	rrs, err := rrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(rrs) {
	case 1:
		return rrs[0], nil
	case 0:
		return nil, &NotFoundError{rolerole.Label}
	default:
		return nil, &NotSingularError{rolerole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rrq *RoleRoleQuery) OnlyX(ctx context.Context) *RoleRole {
	rr, err := rrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return rr
}

// OnlyID returns the only RoleRole id in the query, returns an error if not exactly one id was returned.
func (rrq *RoleRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = &NotSingularError{rolerole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rrq *RoleRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := rrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoleRoles.
func (rrq *RoleRoleQuery) All(ctx context.Context) ([]*RoleRole, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rrq *RoleRoleQuery) AllX(ctx context.Context) []*RoleRole {
	rrs, err := rrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return rrs
}

// IDs executes the query and returns a list of RoleRole ids.
func (rrq *RoleRoleQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rrq.Select(rolerole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rrq *RoleRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := rrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rrq *RoleRoleQuery) Count(ctx context.Context) (int, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rrq *RoleRoleQuery) CountX(ctx context.Context) int {
	count, err := rrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rrq *RoleRoleQuery) Exist(ctx context.Context) (bool, error) {
	if err := rrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rrq *RoleRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := rrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rrq *RoleRoleQuery) Clone() *RoleRoleQuery {
	return &RoleRoleQuery{
		config:     rrq.config,
		limit:      rrq.limit,
		offset:     rrq.offset,
		order:      append([]OrderFunc{}, rrq.order...),
		unique:     append([]string{}, rrq.unique...),
		predicates: append([]predicate.RoleRole{}, rrq.predicates...),
		// clone intermediate query.
		sql:  rrq.sql.Clone(),
		path: rrq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoleRole.Query().
//		GroupBy(rolerole.FieldOwnerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rrq *RoleRoleQuery) GroupBy(field string, fields ...string) *RoleRoleGroupBy {
	group := &RoleRoleGroupBy{config: rrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rrq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//	}
//
//	client.RoleRole.Query().
//		Select(rolerole.FieldOwnerID).
//		Scan(ctx, &v)
//
func (rrq *RoleRoleQuery) Select(field string, fields ...string) *RoleRoleSelect {
	selector := &RoleRoleSelect{config: rrq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rrq.sqlQuery(), nil
	}
	return selector
}

func (rrq *RoleRoleQuery) prepareQuery(ctx context.Context) error {
	if rrq.path != nil {
		prev, err := rrq.path(ctx)
		if err != nil {
			return err
		}
		rrq.sql = prev
	}
	return nil
}

func (rrq *RoleRoleQuery) sqlAll(ctx context.Context) ([]*RoleRole, error) {
	var (
		nodes = []*RoleRole{}
		_spec = rrq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &RoleRole{config: rrq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, rrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rrq *RoleRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rrq.querySpec()
	return sqlgraph.CountNodes(ctx, rrq.driver, _spec)
}

func (rrq *RoleRoleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (rrq *RoleRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rolerole.Table,
			Columns: rolerole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rolerole.FieldID,
			},
		},
		From:   rrq.sql,
		Unique: true,
	}
	if ps := rrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rrq *RoleRoleQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(rrq.driver.Dialect())
	t1 := builder.Table(rolerole.Table)
	selector := builder.Select(t1.Columns(rolerole.Columns...)...).From(t1)
	if rrq.sql != nil {
		selector = rrq.sql
		selector.Select(selector.Columns(rolerole.Columns...)...)
	}
	for _, p := range rrq.predicates {
		p(selector)
	}
	for _, p := range rrq.order {
		p(selector)
	}
	if offset := rrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleRoleGroupBy is the builder for group-by RoleRole entities.
type RoleRoleGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rrgb *RoleRoleGroupBy) Aggregate(fns ...AggregateFunc) *RoleRoleGroupBy {
	rrgb.fns = append(rrgb.fns, fns...)
	return rrgb
}

// Scan applies the group-by query and scan the result into the given value.
func (rrgb *RoleRoleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rrgb.path(ctx)
	if err != nil {
		return err
	}
	rrgb.sql = query
	return rrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rrgb.fields) > 1 {
		return nil, errors.New("ent: RoleRoleGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) StringsX(ctx context.Context) []string {
	v, err := rrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) StringX(ctx context.Context) string {
	v, err := rrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rrgb.fields) > 1 {
		return nil, errors.New("ent: RoleRoleGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) IntsX(ctx context.Context) []int {
	v, err := rrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) IntX(ctx context.Context) int {
	v, err := rrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rrgb.fields) > 1 {
		return nil, errors.New("ent: RoleRoleGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rrgb.fields) > 1 {
		return nil, errors.New("ent: RoleRoleGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (rrgb *RoleRoleGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rrgb *RoleRoleGroupBy) BoolX(ctx context.Context) bool {
	v, err := rrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rrgb *RoleRoleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rrgb.sqlQuery().Query()
	if err := rrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rrgb *RoleRoleGroupBy) sqlQuery() *sql.Selector {
	selector := rrgb.sql
	columns := make([]string, 0, len(rrgb.fields)+len(rrgb.fns))
	columns = append(columns, rrgb.fields...)
	for _, fn := range rrgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(rrgb.fields...)
}

// RoleRoleSelect is the builder for select fields of RoleRole entities.
type RoleRoleSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (rrs *RoleRoleSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := rrs.path(ctx)
	if err != nil {
		return err
	}
	rrs.sql = query
	return rrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rrs *RoleRoleSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rrs.fields) > 1 {
		return nil, errors.New("ent: RoleRoleSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rrs *RoleRoleSelect) StringsX(ctx context.Context) []string {
	v, err := rrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rrs *RoleRoleSelect) StringX(ctx context.Context) string {
	v, err := rrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rrs.fields) > 1 {
		return nil, errors.New("ent: RoleRoleSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rrs *RoleRoleSelect) IntsX(ctx context.Context) []int {
	v, err := rrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rrs *RoleRoleSelect) IntX(ctx context.Context) int {
	v, err := rrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rrs.fields) > 1 {
		return nil, errors.New("ent: RoleRoleSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rrs *RoleRoleSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rrs *RoleRoleSelect) Float64X(ctx context.Context) float64 {
	v, err := rrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rrs.fields) > 1 {
		return nil, errors.New("ent: RoleRoleSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rrs *RoleRoleSelect) BoolsX(ctx context.Context) []bool {
	v, err := rrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (rrs *RoleRoleSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rolerole.Label}
	default:
		err = fmt.Errorf("ent: RoleRoleSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rrs *RoleRoleSelect) BoolX(ctx context.Context) bool {
	v, err := rrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rrs *RoleRoleSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rrs.sqlQuery().Query()
	if err := rrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rrs *RoleRoleSelect) sqlQuery() sql.Querier {
	selector := rrs.sql
	selector.Select(selector.Columns(rrs.fields...)...)
	return selector
}
