// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/predicate"
	"github.com/suisrc/zgo/app/model/ent/rolerole"
)

// RoleRoleDelete is the builder for deleting a RoleRole entity.
type RoleRoleDelete struct {
	config
	hooks      []Hook
	mutation   *RoleRoleMutation
	predicates []predicate.RoleRole
}

// Where adds a new predicate to the delete builder.
func (rrd *RoleRoleDelete) Where(ps ...predicate.RoleRole) *RoleRoleDelete {
	rrd.predicates = append(rrd.predicates, ps...)
	return rrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rrd *RoleRoleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rrd.hooks) == 0 {
		affected, err = rrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoleRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rrd.mutation = mutation
			affected, err = rrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rrd.hooks) - 1; i >= 0; i-- {
			mut = rrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rrd *RoleRoleDelete) ExecX(ctx context.Context) int {
	n, err := rrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rrd *RoleRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rolerole.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rolerole.FieldID,
			},
		},
	}
	if ps := rrd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rrd.driver, _spec)
}

// RoleRoleDeleteOne is the builder for deleting a single RoleRole entity.
type RoleRoleDeleteOne struct {
	rrd *RoleRoleDelete
}

// Exec executes the deletion query.
func (rrdo *RoleRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := rrdo.rrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rolerole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rrdo *RoleRoleDeleteOne) ExecX(ctx context.Context) {
	rrdo.rrd.ExecX(ctx)
}
