// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/suisrc/zgo/app/model/ent/predicate"
	"github.com/suisrc/zgo/app/model/ent/userrole"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks      []Hook
	mutation   *UserRoleMutation
	predicates []predicate.UserRole
}

// Where adds a new predicate for the builder.
func (uru *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	uru.predicates = append(uru.predicates, ps...)
	return uru
}

// SetUserID sets the user_id field.
func (uru *UserRoleUpdate) SetUserID(i int) *UserRoleUpdate {
	uru.mutation.ResetUserID()
	uru.mutation.SetUserID(i)
	return uru
}

// AddUserID adds i to user_id.
func (uru *UserRoleUpdate) AddUserID(i int) *UserRoleUpdate {
	uru.mutation.AddUserID(i)
	return uru
}

// SetRoleID sets the role_id field.
func (uru *UserRoleUpdate) SetRoleID(i int) *UserRoleUpdate {
	uru.mutation.ResetRoleID()
	uru.mutation.SetRoleID(i)
	return uru
}

// AddRoleID adds i to role_id.
func (uru *UserRoleUpdate) AddRoleID(i int) *UserRoleUpdate {
	uru.mutation.AddRoleID(i)
	return uru
}

// SetExpired sets the expired field.
func (uru *UserRoleUpdate) SetExpired(t time.Time) *UserRoleUpdate {
	uru.mutation.SetExpired(t)
	return uru
}

// SetCreator sets the creator field.
func (uru *UserRoleUpdate) SetCreator(s string) *UserRoleUpdate {
	uru.mutation.SetCreator(s)
	return uru
}

// SetCreatedAt sets the created_at field.
func (uru *UserRoleUpdate) SetCreatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetCreatedAt(t)
	return uru
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableCreatedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetCreatedAt(*t)
	}
	return uru
}

// SetUpdatedAt sets the updated_at field.
func (uru *UserRoleUpdate) SetUpdatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableUpdatedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetUpdatedAt(*t)
	}
	return uru
}

// SetVersion sets the version field.
func (uru *UserRoleUpdate) SetVersion(i int) *UserRoleUpdate {
	uru.mutation.ResetVersion()
	uru.mutation.SetVersion(i)
	return uru
}

// SetNillableVersion sets the version field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableVersion(i *int) *UserRoleUpdate {
	if i != nil {
		uru.SetVersion(*i)
	}
	return uru
}

// AddVersion adds i to version.
func (uru *UserRoleUpdate) AddVersion(i int) *UserRoleUpdate {
	uru.mutation.AddVersion(i)
	return uru
}

// Mutation returns the UserRoleMutation object of the builder.
func (uru *UserRoleUpdate) Mutation() *UserRoleMutation {
	return uru.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uru *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uru.hooks) == 0 {
		affected, err = uru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uru.mutation = mutation
			affected, err = uru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uru.hooks) - 1; i >= 0; i-- {
			mut = uru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uru *UserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userrole.FieldID,
			},
		},
	}
	if ps := uru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldUserID,
		})
	}
	if value, ok := uru.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldUserID,
		})
	}
	if value, ok := uru.mutation.RoleID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldRoleID,
		})
	}
	if value, ok := uru.mutation.AddedRoleID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldRoleID,
		})
	}
	if value, ok := uru.mutation.Expired(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldExpired,
		})
	}
	if value, ok := uru.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userrole.FieldCreator,
		})
	}
	if value, ok := uru.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldCreatedAt,
		})
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldUpdatedAt,
		})
	}
	if value, ok := uru.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldVersion,
		})
	}
	if value, ok := uru.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldVersion,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetUserID sets the user_id field.
func (uruo *UserRoleUpdateOne) SetUserID(i int) *UserRoleUpdateOne {
	uruo.mutation.ResetUserID()
	uruo.mutation.SetUserID(i)
	return uruo
}

// AddUserID adds i to user_id.
func (uruo *UserRoleUpdateOne) AddUserID(i int) *UserRoleUpdateOne {
	uruo.mutation.AddUserID(i)
	return uruo
}

// SetRoleID sets the role_id field.
func (uruo *UserRoleUpdateOne) SetRoleID(i int) *UserRoleUpdateOne {
	uruo.mutation.ResetRoleID()
	uruo.mutation.SetRoleID(i)
	return uruo
}

// AddRoleID adds i to role_id.
func (uruo *UserRoleUpdateOne) AddRoleID(i int) *UserRoleUpdateOne {
	uruo.mutation.AddRoleID(i)
	return uruo
}

// SetExpired sets the expired field.
func (uruo *UserRoleUpdateOne) SetExpired(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetExpired(t)
	return uruo
}

// SetCreator sets the creator field.
func (uruo *UserRoleUpdateOne) SetCreator(s string) *UserRoleUpdateOne {
	uruo.mutation.SetCreator(s)
	return uruo
}

// SetCreatedAt sets the created_at field.
func (uruo *UserRoleUpdateOne) SetCreatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetCreatedAt(t)
	return uruo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableCreatedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetCreatedAt(*t)
	}
	return uruo
}

// SetUpdatedAt sets the updated_at field.
func (uruo *UserRoleUpdateOne) SetUpdatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetUpdatedAt(*t)
	}
	return uruo
}

// SetVersion sets the version field.
func (uruo *UserRoleUpdateOne) SetVersion(i int) *UserRoleUpdateOne {
	uruo.mutation.ResetVersion()
	uruo.mutation.SetVersion(i)
	return uruo
}

// SetNillableVersion sets the version field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableVersion(i *int) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetVersion(*i)
	}
	return uruo
}

// AddVersion adds i to version.
func (uruo *UserRoleUpdateOne) AddVersion(i int) *UserRoleUpdateOne {
	uruo.mutation.AddVersion(i)
	return uruo
}

// Mutation returns the UserRoleMutation object of the builder.
func (uruo *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return uruo.mutation
}

// Save executes the query and returns the updated entity.
func (uruo *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	var (
		err  error
		node *UserRole
	)
	if len(uruo.hooks) == 0 {
		node, err = uruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uruo.mutation = mutation
			node, err = uruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uruo.hooks) - 1; i >= 0; i-- {
			mut = uruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	ur, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ur
}

// Exec executes the query on the entity.
func (uruo *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uruo *UserRoleUpdateOne) sqlSave(ctx context.Context) (ur *UserRole, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userrole.FieldID,
			},
		},
	}
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserRole.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := uruo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldUserID,
		})
	}
	if value, ok := uruo.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldUserID,
		})
	}
	if value, ok := uruo.mutation.RoleID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldRoleID,
		})
	}
	if value, ok := uruo.mutation.AddedRoleID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldRoleID,
		})
	}
	if value, ok := uruo.mutation.Expired(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldExpired,
		})
	}
	if value, ok := uruo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userrole.FieldCreator,
		})
	}
	if value, ok := uruo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldCreatedAt,
		})
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userrole.FieldUpdatedAt,
		})
	}
	if value, ok := uruo.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldVersion,
		})
	}
	if value, ok := uruo.mutation.AddedVersion(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: userrole.FieldVersion,
		})
	}
	ur = &UserRole{config: uruo.config}
	_spec.Assign = ur.assignValues
	_spec.ScanValues = ur.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ur, nil
}
